### ISSUE TITLE
"cannot use Debugger literal (type *Debugger) as type Debugger in assignment"

### ISSUE THREAD

**Issue by rkakrik** [shimberger/golang-hls#1]
# command-line-arguments
./debug.go:16: cannot use Debugger literal (type *Debugger) as type Debugger in assignment

**Comment by rkakrik** [comment]
Some dirty hack:
```golang
//var debug Debugger = &Debugger{}
var debug Debugger = Debugger{}
```

**Comment by shimberger** [comment]
Thanks I'll look into it. This thing was something I didn't understand in the first place anyway ;). So maybe it's better to remove anyway.

**Comment by shimberger** [comment]
I fixed and it should at least compile now. May I ask what you are trying to do? This project is pretty much just some stuff I played around with to learn some go and understand how HLS works. Your welcome to try it out and help out though. Just trying to set the right expectations ;).

**Comment by shimberger** [comment]
I'm gonna close this.
