### ISSUE TITLE
entire page is blank

### ISSUE THREAD

**Issue by omgbox** [shimberger/golang-hls#2]
the page is all white, nothing there. i added ffmpeg in tools and ffprobe. go 1.3

>go run *.go ~/mnt

**Comment by shimberger** [comment]
Wow, thanks for trying this thing.

Are you opening http://localhost:8080/ui/ or mayble only http://localhost:8080/ ? I haven't looked at the code in forever but am happy to investigate. Does your browser console output any errors?

**Comment by shimberger** [comment]
I have another idea... the program looks for a folder "videos" in the directory. If you start it by running:

`go run *.go ~/mnt <somepath> `

e.g.

`go run *.go ~/mnt ~/Documents` (on OSX)

it might work.

**Comment by shimberger** [comment]
I also updated the UI to tell you if a folder is empty. So maybe check out the new source code.

**Comment by shimberger** [comment]
@omgbox I'm going to close this issue. Please re-open if not fixed.
